---
- hosts: web
  become: yes
  tasks:

    - name: Enable nginx1 in Amazon Linux Extras
      raw: sudo amazon-linux-extras enable nginx1

    - name: Install NGINX
      raw: sudo yum install -y nginx

    - name: Start NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
