apiVersion: apps/v1
kind: Deployment
metadata:
  name: xops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xops-web
  template:
    metadata:
      labels:
        app: xops-web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: web-content
        configMap:
          name: xops-web-content
---
apiVersion: v1
kind: Service
metadata:
  name: xops-web
spec:
  type: NodePort
  selector:
    app: xops-web
  ports:
  - port: 80
    targetPort: 80
