apiVersion: apps/v1
kind: Deployment
metadata:
  name: xops-app
  labels:
    app: xops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xops-app
  template:
    metadata:
      labels:
        app: xops-app
    spec:
      containers:
      - name: xops-app
        image: YOUR_DOCKERHUB_USER/xops-app:latest
        ports:
        - containerPort: 80
