apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hemanithin22/Xops.git
    targetRevision: main
    path: k8n
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
